In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 

c:\Users\Parth\miniconda3\envs\tftorch\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
c:\Users\Parth\miniconda3\envs\tftorch\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
scalar = torch.tensor(7)
scalar.ndim

0

In [8]:
vector = torch.tensor([7,7,6,4])
vector.shape

torch.Size([4])

In [11]:
matrix = torch.tensor([[1,2],[3,4]])
matrix.shape

torch.Size([2, 2])

In [23]:
tensor = torch.tensor([[[1,2,3],[3,6,9],[5,1,4]], [[1,2,3],[3,6,9],[5,1,4]]])

tensor(1)

In [28]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6028, 0.0239, 0.0903, 0.1448],
        [0.1965, 0.7747, 0.5988, 0.6139],
        [0.4930, 0.8498, 0.4481, 0.9891]])

In [29]:
random_iamge = torch.rand(size=(224,224,3))


In [37]:
zero = torch.zeros(3,4)
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [44]:
int_32 = torch.tensor([3,6,9], dtype=torch.int32)
fl_32 = torch.tensor([3,6,9], dtype=torch.float32)
int_32*fl_32

tensor([ 9., 36., 81.])

In [55]:
torch.matmul(int_32,int_32)

tensor(126, dtype=torch.int32)

In [64]:
x = torch.arange(0,10)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [70]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
z = x.view(1,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
torch.stack([x,x,x], dim=1)

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [94]:
x.unsqueeze(dim=1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [100]:
random_iamge.permute(2,0,1).shape

torch.Size([3, 224, 224])

In [101]:
random_iamge.shape

torch.Size([224, 224, 3])

In [106]:
array = np.arange(0,10)
tensor = torch.from_numpy(array)
array, tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [128]:
A = torch.rand(3,4)
B = torch.rand(3,4)
A==B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [148]:
R_SEED = 42
torch.manual_seed(R_SEED)
C = torch.rand(3,4)
torch.manual_seed(R_SEED)
D = torch.rand(3,4)
C==D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [149]:
C

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])